name: bar

on:
  workflow_dispatch:

jobs:

  barbar:
  
    name: bar bar
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    
    runs-on: ${{ matrix.os }}
    
    steps:
            
    - name: AAA (Windows)
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        dir .
        dir^
            ..
        
    - name: AAA (Linux)
      if: ${{ runner.os == 'Linux' }}
      run: |
        ls -la .
        ls -la\
            ..
        
    - name: Test output
      run: |
        echo asd
        echo asd ERROR
        echo asd [ERROR]
        echo asd [ERROR] asd
        echo [ERROR] asd
        echo ERROR asd
        echo asd ERROR asd
        echo foo [bar]
        echo foo [error]
        echo ::group::ASD
        echo start ASD
        echo ::group::QWE
        echo in QWE
        echo ::endgroup::QWE
        echo end ASD
        echo ::endgroup::ASD
        echo out ASD
