name: bar

on:
  workflow_dispatch:

jobs:

  barbar:

    name: bar bar
    runs-on: ubuntu-latest
    steps:
    
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: "3.10"
        
    - name: Test output
      run: |
        echo asd
        echo asd ERROR
        echo asd [ERROR]
        echo asd [ERROR] asd
        echo [ERROR] asd
        echo ERROR asd
        echo asd ERROR asd
        echo foo [bar]
        echo foo [error]
        echo ::group::ASD
        echo start ASD
        echo ::group::QWE
        echo in QWE
        echo ::endgroup::QWE
        echo end ASD
        echo ::endgroup::ASD
        echo out ASD
