name: input-and-label-caller-test

on:
  pull_request:
    types: ["opened", "synchronize", "reopened", "labeled", "unlabeled"]

jobs:
  list-xxx:
    uses: ./.github/workflows/input-and-label-test.yml
    with:
      xxx: ${{ toJSON(github.event.pull_request.labels.*.name) }}

  doit:
    needs: [list-xxx]

    runs-on: ["ubuntu-latest"]
    timeout-minutes: 180

    strategy:
      fail-fast: false
      matrix:
        mxxx: ${{ needs.list-xxx.outputs.selected }}

    steps:
    - name: Do it
      run: |
          echo ASD
          cat - << --EOF--
          ${{ toJSON(needs.list-xxx.outputs) }}
          --EOF--
          echo ASD
          python -c 'import json;import sys;print(json.loads(sys.argv[1]))' ${{ toJSON(needs.list-xxx.outputs.selected) }}
          echo ASD
          echo ${{ matrix.mxxx }}
