name: input-and-label-test

on:
  workflow_call:
    inputs:
      xxx:
        description: '??? ???'
        required: false
        type: string
    outputs:
      selected:
        description: "selected Xs"
        value: ${{ jobs.list-xxx.outputs.selected }}

jobs:
  list-xxx:
    runs-on: [ "ubuntu-latest" ]
    outputs:
      selected: ${{ steps.list-xxx.outputs.selected }}

    steps:
      - name: List xxx
        id: list-xxx
        run: |
          set -x
          inputs_xxx=$( echo '${{ inputs.xxx }}' | jq -c . )
          if [[ $inputs_xxx == "[]" ]]; then
            allxxx="[\"X1\", \"X2\", \"X3\"]"
            echo "selected=$allxxxx" >> "$GITHUB_OUTPUT"
          else
            echo "selected=${inputs_xxx}" >> "$GITHUB_OUTPUT"
          fi
          echo 'GITHUB_OUTPUT:'
          cat $GITHUB_OUTPUT
