name: input-and-label-test

on:
  pull_request:
    types: ["opened", "synchronize", "reopened", "labeled", "unlabeled"]
  workflow_dispatch:
    inputs:
      xxx:
        description: 'List of xxx'
        required: false
        default: ''

jobs:
  list-xxx:

    if: ${{ !inputs.xxx }}

    runs-on: [ "ubuntu-latest" ]
    outputs:
      all-xxx: ${{ steps.list-xxx.outputs.all-xxx }}
      labeled-xxx: ${{ steps.list-xxx.outputs.labeled-xxx }}

    steps:
      - name: List xxx
        id: list-xxxx
        run: |
          echo "all-xxx=[\"X1\", \"X2\", \"X3\"]" >> "$GITHUB_OUTPUT"
          echo "labeled-xxx=${{ join(github.event.pull_request.labels.*.name) }}" >> "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
          echo 'inputs.xxx=${{ inputs.xxx }}'

  doit:
    needs: [list-xxx]

    runs-on: ["ubuntu-latest"]
    timeout-minutes: 180

    strategy:
      fail-fast: false
      matrix:
        xxx: ${{ fromJSON( inputs.xxx || needs.list-runners.outputs.labeled-xxx || needs.list-runners.outputs.all-xxx ) }}

    - name: Do it
      run: |
          echo ASD
          echo ${{ matrix.xxx }}
          echo ASD
