name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/labeler@v5
      id: label-pr
      
    - name: Inspect Labels
      env:
        NEW_LABELS: ${{ steps.label-pr.outputs.new-labels }}
        ALL_LABELS: ${{ steps.label-pr.outputs.all-labels }}
      run: |        
        if [ -z "$NEW_LABELS" ]; then
          echo "No new labels were applied in this run."
        else
          echo "New Labels Applied: $NEW_LABELS"
        fi
        
        echo "All Current Labels: $ALL_LABELS"
    
