name: Test

on:
  pull_request:
  
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Run...
      run: |
        python -c "import os;print('\n'.join(f'{k}: {v}' for k, v in os.environ.items()))"
